### ISSUE TITLE
start date on create event can't use today's date

### ISSUE THREAD

**Issue by theodevoid** [entry-point-community/mabar-fun#10]

**Comment by pras-wjy** [comment]
sudah aku PR bang ( #12 ), tapi belum aku test hehe. mohon direview, kalo emang udah bener tolong dimerge ya bang, supaya aku terlihat keren karena sudah pernah kontribusi di sebuah projek open source.

terima kasih 🙏

**Comment by theodevoid** [comment]
Fixed in #12
