### ISSUE TITLE
Wrong MLBB user id validation in edit profile page

### ISSUE THREAD

**Issue by pras-wjy** [entry-point-community/mabar-fun#14]
user id aku panjangnya 7, tapi toast errornya bilang minimal 8.

TAPI, di validasi zodnya kok aku cek malah minimal 4 karakter ya?

**Comment by pras-wjy** [comment]
![image](https://github.com/entry-point-community/mabar-fun/assets/36604747/b918e8d6-c192-4a90-8399-d73eb472e9dd)

**Comment by halowahyudi** [comment]
fixes #24

**Comment by theodevoid** [comment]
Fixed in #24

**Comment by pras-wjy** [comment]
masih dapet toast error yang sama, kayaknya emang bug dari API Games nya gak sih?

**Comment by theodevoid** [comment]
> masih dapet toast error yang sama, kayaknya emang bug dari API Games nya gak sih?

Damn, anda benar. Reopening..
