### ISSUE TITLE
Failed fetch user data after Authenticated

### ISSUE THREAD

**Issue by Riskev02** [entry-point-community/mabar-fun#19]
endpointnya yang ini bang:
https://api-mabar.voidfnc.com/profiles
response : 
-status_code: 404 Not Found
-response_data : {"errors":["profile not found"]}

ss:
<img width="1440" alt="image" src="https://github.com/entry-point-community/mabar-fun/assets/87601225/5704652f-6860-4027-8f23-9dd7e172e0da">

btw sorry bang theo kalo gaterlalu ngedescribe

**Comment by theodevoid** [comment]
Fixed in #26
