### ISSUE TITLE
API Cek Nickname Game (MLBB)

### ISSUE THREAD

**Issue by halowahyudi** [entry-point-community/mabar-fun#4]
Kebetulan gua ada APInya daripada bayar 5 Rupiah percek di provider lain.. gua juga udah DM lu.

**Comment by theodevoid** [comment]
gue sama bang dea udah nemu dan daftar buat API-nya broo, tapi thanks buat infonya. Kalau mau bantu implementasi service-nya di backend kita silahkan, gue bakal keep issue ini open. Tapi kalo engga, ini gue close aja yaa. 💯
